### ISSUE TITLE
Gem and Bundle both fail :/

### ISSUE THREAD

**Issue by palladius** [parasquid/activerecord-gsheets-adapter#1]
$ 🐧  gem install activerecord-gsheets-adapter
ERROR:  Could not find a valid gem 'activerecord-gsheets-adapter' (>= 0) in any repository
ERROR:  Possible alternatives: activerecord-ingres-adapter, activerecord-crate-adapter, activerecord-hbase-adapter, activerecord-hive-adapter, activerecord-postgis-adapter

$ 🐧  gem -v
2.7.6

# from bundle after adding gem 'activerecord-gsheets-adapter'
 
Looking up gems ["bundler", "activerecord-gsheets-adapter"]
Could not find gem 'activerecord-gsheets-adapter' in any of the gem sources listed in your Gemfile.
Bundler::GemNotFound: Could not find gem 'activerecord-gsheets-adapter' in any of the gem sources listed in your Gemfile.
/home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/resolver.rb:255:in `each'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/resolver.rb:255:in `verify_gemfile_dependencies_are_found!'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/resolver.rb:49:in `start'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/resolver.rb:22:in `resolve'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:259:in `resolve'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:171:in `specs'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/definition.rb:159:in `resolve_remotely!'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/installer.rb:287:in `resolve_if_needed'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/installer.rb:83:in `block in run'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/process_lock.rb:12:in `block in lock'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/process_lock.rb:9:in `open'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/process_lock.rb:9:in `lock'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/installer.rb:72:in `run'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/installer.rb:25:in `install'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli/install.rb:65:in `run'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli.rb:224:in `block in install'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/settings.rb:136:in `temporary'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli.rb:223:in `install'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli.rb:27:in `dispatch'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/cli.rb:18:in `start'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/exe/bundle:30:in `block in <top (required)>'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
  /home/riccardo/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/exe/bundle:22:in `<top (required)>'
  /home/riccardo/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
  /home/riccardo/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'

**Comment by lulalala** [comment]
@palladius The owner probably never officially released this to rubygems.org.

If you want to try it, use `gem 'activerecord-gsheets-adapter, github: "parasquid/activerecord-gsheets-adapter"`
